# Generated by Django 5.0.1 on 2024-02-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchedAnime',
        ),
    ]
