# Generated by Django 5.0.1 on 2024-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watched_Anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedanime',
            name='site',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
