# Generated by Django 5.0.1 on 2024-02-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watched_Anime', '0002_watchedanime_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedanime',
            name='anime_id',
            field=models.IntegerField(default=0),
        ),
    ]
