# Generated by Django 5.0.1 on 2024-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watched_Anime', '0003_watchedanime_anime_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedanime',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
