# Generated by Django 5.0.1 on 2024-02-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watched_Anime', '0004_watchedanime_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedanime',
            name='anime_id',
        ),
    ]
